### ISSUE TITLE
Notedeck builds, but won't run

### ISSUE THREAD

**Issue by derekross** [damus-io/notedeck#141]
i am trying to build and run the code for notedeck and unable to do so. the following is the output i receive.

`[nix-shell:~/damus/notedeck]$ cargo run --release 
    Updating git repository `https://github.com/damus-io/egui-nav`
    Updating git repository `https://github.com/damus-io/nostrdb-rs`
    Updating git submodule `https://github.com/damus-io/nostrdb`
    Updating git submodule `https://github.com/bitcoin-core/secp256k1`
   Compiling secp256k1 v0.28.2
   Compiling nostrdb v0.3.4 (https://github.com/damus-io/nostrdb-rs?rev=ee8afeeb0b6695fca6d27dd0b74a8dc159e37b95#ee8afeeb)
   Compiling egui_nav v0.1.0 (https://github.com/damus-io/egui-nav?rev=0498cbee12935448478823d855060dc749a0b8b6#0498cbee)
   Compiling bitcoin v0.31.2
   Compiling nostr v0.30.0
   Compiling enostr v0.1.0 (/home/derek/damus/notedeck/enostr)
   Compiling notedeck v0.1.0 (/home/derek/damus/notedeck)
    Finished `release` profile [optimized] target(s) in 1m 42s
     Running `target/release/notedeck`
2024-07-02T19:27:32.336866Z  INFO eframe: Both the glow and wgpu renderers are available. Using wgpu.    
2024-07-02T19:27:32.352390Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1    
2024-07-02T19:27:32.362636Z  WARN wgpu_hal::vulkan::instance: Unable to find extension: VK_KHR_surface    
2024-07-02T19:27:32.362748Z  WARN wgpu_hal::vulkan::instance: Unable to find extension: VK_KHR_xlib_surface    
2024-07-02T19:27:32.362815Z  WARN wgpu_hal::vulkan::instance: Unable to find extension: VK_KHR_xcb_surface    
2024-07-02T19:27:32.362879Z  WARN wgpu_hal::vulkan::instance: Unable to find extension: VK_KHR_wayland_surface    
2024-07-02T19:27:32.362944Z  WARN wgpu_hal::vulkan::instance: Unable to find extension: VK_EXT_swapchain_colorspace    
2024-07-02T19:27:32.363008Z  WARN wgpu_hal::vulkan::instance: Unable to find extension: VK_KHR_get_physical_device_properties2    
2024-07-02T19:27:32.366294Z  WARN wgpu_hal::gles::egl: EGL_MESA_platform_surfaceless not available. Using default platform    
thread 'main' panicked at /home/derek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.19.1/src/gles/egl.rs:799:88:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by alltheseas** [comment]
Which OS?

**Comment by derekross** [comment]
Elementary OS 7.1. I also get the same error on Windows 11 WSL 2.0. Both are Debian / Ubuntu derivatives.

**Comment by jb55** [comment]
can you try master and see if it fixes it?

**Comment by derekross** [comment]
`2024-07-02T23:58:10.044994Z ERROR eframe::native::run: Exiting because of error: Found no glutin configs matching the template: ConfigTemplate { color_buffer_type: Rgb { r_size: 8, g_size: 8, b_size: 8 }, alpha_size: 8, depth_size: 0, stencil_size: 0, num_samples: None, min_swap_interval: None, max_swap_interval: None, config_surface_types: ConfigSurfaceTypes(WINDOW), api: None, transparency: false, single_buffering: false, stereoscopy: None, float_pixels: false, max_pbuffer_width: None, hardware_accelerated: None, max_pbuffer_height: None, native_window: None }. Error: Error { raw_code: None, raw_os_message: None, kind: BadConfig } during event Resumed`

**Comment by jb55** [comment]
can you fetch again and try this branch: 

`git switch egui-0.28`

**Comment by jb55** [comment]
I've updated to the latest wgpu from egui which should fix weird gfx issues, feel free to re-open if there's still an issue

**Comment by derekross** [comment]
still getting errors.

2024-07-03T01:01:37.052160Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1    
2024-07-03T01:01:37.086754Z  WARN wgpu_hal::vulkan::instance: Unable to find extension: VK_KHR_surface    
2024-07-03T01:01:37.086817Z  WARN wgpu_hal::vulkan::instance: Unable to find extension: VK_KHR_xlib_surface    
2024-07-03T01:01:37.086841Z  WARN wgpu_hal::vulkan::instance: Unable to find extension: VK_KHR_xcb_surface    
2024-07-03T01:01:37.086899Z  WARN wgpu_hal::vulkan::instance: Unable to find extension: VK_KHR_wayland_surface    
2024-07-03T01:01:37.086915Z  WARN wgpu_hal::vulkan::instance: Unable to find extension: VK_EXT_swapchain_colorspace    
2024-07-03T01:01:37.086928Z  WARN wgpu_hal::vulkan::instance: Unable to find extension: VK_KHR_get_physical_device_properties2    
2024-07-03T01:01:37.095524Z  WARN wgpu_hal::gles::egl: EGL_MESA_platform_surfaceless not available. Using default platform    
thread 'main' panicked at /home/raven/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/egl.rs:850:88:
called `Option::unwrap()` on a `None` value

**Comment by derekross** [comment]
still getting errors

2024-07-03T01:01:37.052160Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1    
2024-07-03T01:01:37.086754Z  WARN wgpu_hal::vulkan::instance: Unable to find extension: VK_KHR_surface    
2024-07-03T01:01:37.086817Z  WARN wgpu_hal::vulkan::instance: Unable to find extension: VK_KHR_xlib_surface    
2024-07-03T01:01:37.086841Z  WARN wgpu_hal::vulkan::instance: Unable to find extension: VK_KHR_xcb_surface    
2024-07-03T01:01:37.086899Z  WARN wgpu_hal::vulkan::instance: Unable to find extension: VK_KHR_wayland_surface    
2024-07-03T01:01:37.086915Z  WARN wgpu_hal::vulkan::instance: Unable to find extension: VK_EXT_swapchain_colorspace    
2024-07-03T01:01:37.086928Z  WARN wgpu_hal::vulkan::instance: Unable to find extension: VK_KHR_get_physical_device_properties2    
2024-07-03T01:01:37.095524Z  WARN wgpu_hal::gles::egl: EGL_MESA_platform_surfaceless not available. Using default platform    
thread 'main' panicked at /home/derek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/egl.rs:850:88:
called `Option::unwrap()` on a `None` value

**Comment by jb55** [comment]
I was able to build and run it on elementaryOS:

![VirtualBox_elementaryOS_03_07_2024_08_20_51](https://github.com/damus-io/notedeck/assets/45598/41898d8c-56b9-4d4d-91b2-7bb590e29fb3)

make sure you are not using the nix shell. you just need rustup and build-essential

**Comment by jb55** [comment]
looks like it is a nix-shell issue from your log, closing

**Comment by derekross** [comment]
i didn't even think to try to not use nix-shell for this since i used nix-shell to build the android apk. thanks will. i was able to build and run it normally.

**Comment by jb55** [comment]
I opened a follow up issue here:

- #144

**Comment by jb55** [comment]
@derekross since we don't have docs for this yet, here's some quick commands to get started:

`./target/release/notedeck --sec your_secret_key -f queries/timeline.json -f queries/notifications.json`

you will want to update the query files with your own until we have have automatic timelines working
